version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: experteasedb
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
